# plugins/config.yaml - Main plugin configuration file
plugins:
  # Currently unavailable plugins will bring down the adapter
#   - name: CfDLGuard
#     kind: external
#     hooks: ["tool_pre_invoke", "tool_post_invoke"]
#     mode: enforce
#     mcp:
#       proto: STREAMABLEHTTP
#       url: http://dlguard-plugin-service:8000/mcp
# #      tls:
# #        certfile: /path/to/client-cert.pem
# #        keyfile: /path/to/client-key.pem
# #        ca_bundle: /path/to/ca-bundle.pem
# #        verify: false
  # Nemo example
  - name: "NemoWrapperPlugin"
    kind: "plugins.nemo.nemo_wrapper_plugin.NemoWrapperPlugin"
    description: "A simple Nemo PII detector"
    version: "0.1.0"
    author: "Evaline Ju"
    hooks: ["tool_pre_invoke", "tool_post_invoke"]
    tags: ["plugin", "pre-post"]
    mode: "enforce"  # enforce | permissive | disabled
    priority: 150
    config:
      foo: bar

# Plugin directories to scan
plugin_dirs:
  - "plugins/native"      # Built-in plugins
  - "plugins/custom"      # Custom organization plugins
  - "/etc/mcpgateway/plugins"  # System-wide plugins
  - "plugins/nemo"        # Example Nemo Guardrails plugins

# Global plugin settings
plugin_settings:
  parallel_execution_within_band: true
  plugin_timeout: 30
  fail_on_plugin_error: false
  enable_plugin_api: true
  plugin_health_check_interval: 60
