id: pii-tool-test

models:
  - type: main
    engine: ollama
    model: llama3.2:3b-instruct-fp16
    parameters:
      # Docker ollama instance
      base_url: http://host.docker.internal:11434
rails:
  input:
    flows:
      - detect_pii_on_tool_input
